import { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Building2, Check, ChevronDown, Compass, House, LandPlot, Menu, Search, ShieldCheck, Sofa, Sparkles, Star, Users, X } from "lucide-react";

const image = (id, width = 1200) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=85`;
const featuredProperties = [
  { name: "The Glass House", location: "Runda, Nairobi", price: "KES 48,000,000", type: "For sale", image: image("photo-1600585154340-be6161a56a0c") },
  { name: "Mawingu Residences", location: "Kilimani, Nairobi", price: "KES 115,000 / mo", type: "For rent", image: image("photo-1600607687939-ce8a6c25118c") },
  { name: "Cedar House", location: "Karen, Nairobi", price: "KES 32,500,000", type: "For sale", image: image("photo-1600566753190-17f0baa2a6c3") },
];
const categories = [
  { name: "Houses", count: "1,240 listings", icon: House, image: image("photo-1600585152915-d208bec867a1", 700) },
  { name: "Apartments", count: "860 listings", icon: Building2, image: image("photo-1545324418-cc1a3fa10c00", 700) },
  { name: "Hostels", count: "320 listings", icon: Users, image: image("photo-1555854877-bab0e564b8d5", 700) },
  { name: "Land", count: "540 listings", icon: LandPlot, image: image("photo-1500382017468-9049fed747ef", 700) },
  { name: "Buildings", count: "180 listings", icon: Building2, image: image("photo-1486406146926-c627a92ad1ab", 700) },
  { name: "Furniture", count: "2,400 items", icon: Sofa, image: image("photo-1555041469-a586c61ea9bc", 700) },
];
const steps = [
  { number: "01", title: "Tell us what you need", text: "Set your location, budget and the kind of space you have in mind." },
  { number: "02", title: "Explore with confidence", text: "Compare verified spaces through rich photography, details and real context." },
  { number: "03", title: "Make it yours", text: "Connect directly, book a viewing and move forward without the friction." },
];

function LandingPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  return (
    <main className="landing-page">
      <nav className="landing-nav" aria-label="Main navigation">
        <Link className="brand-mark" to="/" aria-label="PangaEasy home"><span className="brand-symbol">P</span><span>Panga<span>Easy</span></span></Link>
        <div className={`nav-links ${menuOpen ? "is-open" : ""}`}><a href="#discover" onClick={() => setMenuOpen(false)}>Discover</a><a href="#categories" onClick={() => setMenuOpen(false)}>Categories</a><a href="#how-it-works" onClick={() => setMenuOpen(false)}>How it works</a><Link to="/login" className="mobile-login" onClick={() => setMenuOpen(false)}>Sign in</Link></div>
        <div className="nav-actions"><Link to="/login" className="nav-sign-in">Sign in</Link><Link to="/register" className="button button-dark button-small">List a property <ArrowRight size={15} /></Link></div>
        <button className="menu-button" type="button" aria-label="Toggle navigation" onClick={() => setMenuOpen((open) => !open)}>{menuOpen ? <X size={21} /> : <Menu size={21} />}</button>
      </nav>

      <section className="hero-section"><div className="hero-media" /><div className="hero-shade" /><div className="hero-content page-width"><p className="eyebrow hero-eyebrow"><Sparkles size={15} /> A better way to find your place</p><h1>Space to live.<br /><em>Room to grow.</em></h1><p className="hero-copy">Discover homes, hostels, land and spaces that feel like they were made for your next chapter.</p><div className="hero-actions"><a className="button button-accent" href="#discover">Explore properties <ArrowRight size={17} /></a><Link className="button button-ghost-light" to="/register">List your property</Link></div><div className="hero-proof"><div className="avatar-stack"><span>AM</span><span>JK</span><span>LN</span><span>+</span></div><span><strong>12,000+</strong> people found their place with us</span></div></div><div className="hero-caption"><span>01</span><span className="caption-line" /><span>Karura / Nairobi</span></div></section>
      <section className="trust-strip"><div className="page-width trust-inner"><span>TRUSTED BY PEOPLE MOVING FORWARD</span><strong>12k+ <small>spaces listed</small></strong><strong>48 <small>neighbourhoods</small></strong><strong>4.9 <small>customer rating</small></strong></div></section>
      <section className="section page-width" id="discover"><div className="section-heading"><div><p className="eyebrow">Curated for you</p><h2>Find a place<br /><em>worth coming home to.</em></h2></div><Link className="text-link" to="/apartments/browse">View all properties <ArrowRight size={16} /></Link></div><div className="property-grid">{featuredProperties.map((property, index) => <article className={`property-card ${index === 0 ? "property-card-large" : ""}`} key={property.name}><img src={property.image} alt={property.name} loading={index ? "lazy" : "eager"} /><div className="property-gradient" /><span className="property-tag">{property.type}</span><div className="property-info"><div><h3>{property.name}</h3><p>{property.location}</p></div><strong>{property.price}</strong></div></article>)}</div></section>
      <section className="category-section" id="categories"><div className="page-width"><div className="section-heading category-heading"><div><p className="eyebrow">Make it yours</p><h2>Whatever your<br /><em>next looks like.</em></h2></div><p className="section-intro">From a first apartment to a piece of land with a future, PangaEasy brings every possibility into one considered place.</p></div><div className="category-grid">{categories.map(({ name, count, icon: Icon, image: categoryImage }) => <Link to="/apartments/browse" className="category-card" key={name}><img src={categoryImage} alt="" loading="lazy" /><div className="category-overlay" /><div className="category-icon"><Icon size={19} /></div><div className="category-card-info"><h3>{name}</h3><span>{count} <ArrowRight size={14} /></span></div></Link>)}</div></div></section>
      <section className="search-section page-width"><div className="search-copy"><p className="eyebrow">Start somewhere</p><h2>Let the right place<br /><em>come to you.</em></h2><p>Search the way you think about space. By neighbourhood, feeling, budget or simply by what is possible.</p></div><div className="search-panel"><div className="search-tabs"><button className="active" type="button">Buy</button><button type="button">Rent</button><button type="button">Stay</button></div><div className="search-fields"><label>I'm looking for<input placeholder="Apartment, house, land..." /></label><label>Location<div className="select-field">Nairobi, Kenya <ChevronDown size={16} /></div></label><button className="search-button" type="button" aria-label="Search properties"><Search size={20} /></button></div><div className="search-suggestions"><span>Popular searches</span><button type="button">Kilimani</button><button type="button">Karen</button><button type="button">Westlands</button></div></div></section>
      <section className="why-section"><div className="page-width why-grid"><div className="why-image"><img src={image("photo-1600607687920-4e2a09cf159d")} alt="Warm, modern living room" loading="lazy" /><div className="image-note"><span className="note-dot" />Every detail, considered</div></div><div className="why-copy"><p className="eyebrow">Why PangaEasy</p><h2>A little more<br /><em>certain.</em></h2><p className="large-copy">Property decisions are personal. We make them feel clear, informed and distinctly yours.</p><div className="benefit-list"><div><span className="benefit-icon"><ShieldCheck size={19} /></span><span><strong>Verified spaces</strong><small>What you see is what you get, every time.</small></span></div><div><span className="benefit-icon"><Compass size={19} /></span><span><strong>Local insight</strong><small>Explore neighbourhoods through a more human lens.</small></span></div><div><span className="benefit-icon"><Sparkles size={19} /></span><span><strong>Made effortless</strong><small>From first search to final key, fewer dead ends.</small></span></div></div><Link className="text-link" to="/register">Discover PangaEasy <ArrowRight size={16} /></Link></div></div></section>
      <section className="gallery-section page-width"><div className="section-heading"><div><p className="eyebrow">The PangaEasy perspective</p><h2>Good spaces<br /><em>change things.</em></h2></div><p className="section-intro">A home is more than its walls. It is the morning light, the walk downstairs, the room you finally make your own.</p></div><div className="gallery-grid"><img className="gallery-tall" src={image("photo-1600210492486-724fe5c67fb0", 800)} alt="Elegant interior" loading="lazy" /><img src={image("photo-1600566753086-00f18fb6b3ea", 900)} alt="Contemporary kitchen" loading="lazy" /><img src={image("photo-1600607688969-a5bfcd646154", 900)} alt="Bright living area" loading="lazy" /><div className="gallery-quote"><Star size={17} fill="currentColor" /><p>“The search felt less like a transaction and more like finding where I belonged.”</p><span>— Amina, Kilimani</span></div></div></section>
      <section className="steps-section" id="how-it-works"><div className="page-width"><div className="steps-intro"><p className="eyebrow">A simpler journey</p><h2>Good things<br /><em>take shape.</em></h2><p>Everything you need to make a confident move, thoughtfully brought together.</p></div><div className="steps-list">{steps.map((step) => <div className="step" key={step.number}><span className="step-number">{step.number}</span><div><h3>{step.title}</h3><p>{step.text}</p></div><Check size={19} /></div>)}</div></div></section>
      <section className="cta-section page-width"><div className="cta-inner"><div><p className="eyebrow">Your next chapter starts here</p><h2>There is a place<br /><em>for your story.</em></h2></div><Link className="button button-accent" to="/register">Start exploring <ArrowRight size={17} /></Link></div></section>
      <footer className="landing-footer"><div className="page-width footer-grid"><div className="footer-brand"><Link className="brand-mark" to="/"><span className="brand-symbol">P</span><span>Panga<span>Easy</span></span></Link><p>Property, with a little more possibility.</p></div><div><h3>Explore</h3><a href="#discover">Properties</a><a href="#categories">Categories</a><a href="#how-it-works">How it works</a></div><div><h3>For owners</h3><Link to="/register">List a property</Link><Link to="/login">Owner sign in</Link><a href="mailto:hello@pangaeasy.com">Talk to our team</a></div><div><h3>Stay in the know</h3><p className="footer-newsletter-copy">New spaces and considered living, in your inbox.</p><div className="newsletter"><input type="email" placeholder="Your email address" aria-label="Email address" /><button type="button" aria-label="Subscribe"><ArrowRight size={16} /></button></div></div></div><div className="page-width footer-bottom"><span>© 2026 PangaEasy. Made for moving forward.</span><span>Privacy &nbsp; Terms</span></div></footer>
    </main>
  );
}

export default LandingPage;